# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\projects\kiwoon36\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(3940, 2100)
        MainWindow.setMinimumSize(QtCore.QSize(3360, 2100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setAutoScroll(True)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setStyleSheet("QTableWidget{\n"
"background-color:#C0C0C0;\n"
"alternate-background-color:#606060;\n"
"selection-background-color:#282828\n"
"}\n"
"\n"
"QHeaderView::section {background-color:#404040;color:#FFFFFF;}")
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_2.addWidget(self.dateEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.graphArea = matplotlibWidget(self.centralwidget)
        self.graphArea.setMinimumSize(QtCore.QSize(0, 800))
        self.graphArea.setMaximumSize(QtCore.QSize(16777215, 1800))
        self.graphArea.setObjectName("graphArea")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.graphArea)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.graphArea)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 900))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 900))
        self.tabWidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"background-color:#C0C0C0;\n"
"alternate-background-color:#606060;\n"
"selection-background-color:#282828\n"
"}\n"
"\n"
"QHeaderView::section {background-color:#404040;color:#FFFFFF;}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"background-color:#C0C0C0;\n"
"alternate-background-color:#606060;\n"
"selection-background-color:#282828\n"
"}\n"
"\n"
"QHeaderView::section {background-color:#404040;color:#FFFFFF;}")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(19)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout_8.addWidget(self.tableWidget_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setStyleSheet("QTableWidget{\n"
"background-color:#C0C0C0;\n"
"alternate-background-color:#606060;\n"
"selection-background-color:#282828\n"
"}\n"
"\n"
"QHeaderView::section {background-color:#404040;color:#FFFFFF;}")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(91)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(60, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(61, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(62, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(63, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(64, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(65, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(66, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(67, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(68, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(69, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(70, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(71, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(72, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(73, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(74, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(75, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(76, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(77, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(78, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(79, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(80, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(81, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(82, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(83, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(84, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(85, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(86, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(87, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(88, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(89, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(90, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_10.addWidget(self.tableWidget_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_4.setStyleSheet("QTableWidget{\n"
"background-color:#C0C0C0;\n"
"alternate-background-color:#606060;\n"
"selection-background-color:#282828\n"
"}\n"
"\n"
"QHeaderView::section {background-color:#404040;color:#FFFFFF;}")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(128)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(60, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(61, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(62, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(63, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(64, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(65, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(66, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(67, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(68, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(69, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(70, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(71, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(72, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(73, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(74, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(75, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(76, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(77, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(78, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(79, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(80, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(81, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(82, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(83, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(84, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(85, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(86, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(87, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(88, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(89, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(90, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(91, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(92, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(93, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(94, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(95, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(96, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(97, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(98, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(99, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(100, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(101, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(102, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(103, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(104, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(105, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(106, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(107, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(108, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(109, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(110, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(111, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(112, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(113, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(114, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(115, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(116, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(117, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(118, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(119, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(120, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(121, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(122, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(123, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(124, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(125, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(126, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(127, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout_12.addWidget(self.tableWidget_4)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_5.setStyleSheet("QTableWidget{\n"
"background-color:#C0C0C0;\n"
"alternate-background-color:#606060;\n"
"selection-background-color:#282828\n"
"}\n"
"\n"
"QHeaderView::section {background-color:#404040;color:#FFFFFF;}")
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(16)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(223, 219, 86))
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(15, item)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(135)
        self.verticalLayout_14.addWidget(self.tableWidget_5)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.setStretch(2, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3940, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(MainWindow.testSlot)
        self.listWidget.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.testSlotDoubleClick)
        self.pushButton.clicked.connect(MainWindow.search)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tableWidget_4, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tableWidget_2)
        MainWindow.setTabOrder(self.tableWidget_2, self.tableWidget_3)
        MainWindow.setTabOrder(self.tableWidget_3, self.listWidget)
        MainWindow.setTabOrder(self.listWidget, self.treeWidget)
        MainWindow.setTabOrder(self.treeWidget, self.tableWidget_5)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "item1"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "item2"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "item3"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "item4"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "item5"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "item6"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "2"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "3"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "start"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "새 항목"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "새 항목"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "검색조건"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "일자"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "평균단가"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "거래량"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "개인"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "세력합"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "외국인"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "금융투자"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "보험"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "투신"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "기타금융"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "은행"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "연기금"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "사모펀드"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "국가"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "기타법인"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "내외국인"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "매집량 분석표"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "일자"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "현재가"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "전일비"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "등략률"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "거래량"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "개인"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "외국인"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "기관계"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "금융투자"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "보험"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "투신"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "기타금융"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "은행"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "연기금등"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "사모펀드"))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "국가"))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "기타법인"))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "내외국인"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "매집량 거래내역"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "\n"
"일자"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "\n"
"현재가"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "개인\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "외국인/기관합계\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "\n"
"5일추세"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "\n"
"20일추세"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "\n"
"60일추세"))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "외국인\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "금융투자누\n"
"적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "보험\n"
"누적합계\n"
""))
        item = self.tableWidget_3.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "투신\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(32)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(33)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(34)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(35)
        item.setText(_translate("MainWindow", "기타금융\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(36)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(37)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(38)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(39)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(40)
        item.setText(_translate("MainWindow", "은행\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(41)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(42)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(43)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(44)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(45)
        item.setText(_translate("MainWindow", "연기금\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(46)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(47)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(48)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(49)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(50)
        item.setText(_translate("MainWindow", "사모펀드\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(51)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(52)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(53)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(54)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(55)
        item.setText(_translate("MainWindow", "국가\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(56)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(57)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(58)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(59)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(60)
        item.setText(_translate("MainWindow", "기타법인\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(61)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(62)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(63)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(64)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(65)
        item.setText(_translate("MainWindow", "내외국인\n"
"누적합계"))
        item = self.tableWidget_3.horizontalHeaderItem(66)
        item.setText(_translate("MainWindow", "\n"
"최고저점"))
        item = self.tableWidget_3.horizontalHeaderItem(67)
        item.setText(_translate("MainWindow", "\n"
"매집수량"))
        item = self.tableWidget_3.horizontalHeaderItem(68)
        item.setText(_translate("MainWindow", "\n"
"매집고점"))
        item = self.tableWidget_3.horizontalHeaderItem(69)
        item.setText(_translate("MainWindow", "\n"
"분산비율"))
        item = self.tableWidget_3.horizontalHeaderItem(71)
        item.setText(_translate("MainWindow", "세력매집추세\n"
"주가"))
        item = self.tableWidget_3.horizontalHeaderItem(72)
        item.setText(_translate("MainWindow", "\n"
"5일"))
        item = self.tableWidget_3.horizontalHeaderItem(73)
        item.setText(_translate("MainWindow", "\n"
"20일"))
        item = self.tableWidget_3.horizontalHeaderItem(75)
        item.setText(_translate("MainWindow", "세력분산비율추세\n"
"주가"))
        item = self.tableWidget_3.horizontalHeaderItem(76)
        item.setText(_translate("MainWindow", "\n"
"개인분산"))
        item = self.tableWidget_3.horizontalHeaderItem(77)
        item.setText(_translate("MainWindow", "\n"
"세력분산"))
        item = self.tableWidget_3.horizontalHeaderItem(79)
        item.setText(_translate("MainWindow", "보유수량추세\n"
"주가"))
        item = self.tableWidget_3.horizontalHeaderItem(80)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_3.horizontalHeaderItem(81)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_3.horizontalHeaderItem(82)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_3.horizontalHeaderItem(83)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_3.horizontalHeaderItem(84)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_3.horizontalHeaderItem(85)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_3.horizontalHeaderItem(86)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_3.horizontalHeaderItem(87)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_3.horizontalHeaderItem(88)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_3.horizontalHeaderItem(89)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_3.horizontalHeaderItem(90)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "매집량"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "일자"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "주가"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "5일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "\n"
"외국인+기관"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "10일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(25)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(26)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(27)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(28)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(29)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(30)
        item.setText(_translate("MainWindow", "20일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(31)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(32)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(33)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(34)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(35)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(36)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(37)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(38)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(39)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(40)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(41)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(42)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(43)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(44)
        item.setText(_translate("MainWindow", "40일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(45)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(46)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(47)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(48)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(49)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(50)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(51)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(52)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(53)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(54)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(55)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(56)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(57)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(58)
        item.setText(_translate("MainWindow", "60일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(59)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(60)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(61)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(62)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(63)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(64)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(65)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(66)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(67)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(68)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(69)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(70)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(71)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(72)
        item.setText(_translate("MainWindow", "80일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(73)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(74)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(75)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(76)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(77)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(78)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(79)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(80)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(81)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(82)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(83)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(84)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(85)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(86)
        item.setText(_translate("MainWindow", "100일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(87)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(88)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(89)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(90)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(91)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(92)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(93)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(94)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(95)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(96)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(97)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(98)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(99)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(100)
        item.setText(_translate("MainWindow", "120일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(101)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(102)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(103)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(104)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(105)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(106)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(107)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(108)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(109)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(110)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(111)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(112)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(113)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(114)
        item.setText(_translate("MainWindow", "240일추세\n"
"개인"))
        item = self.tableWidget_4.horizontalHeaderItem(115)
        item.setText(_translate("MainWindow", "\n"
"외국인"))
        item = self.tableWidget_4.horizontalHeaderItem(116)
        item.setText(_translate("MainWindow", "\n"
"기관"))
        item = self.tableWidget_4.horizontalHeaderItem(117)
        item.setText(_translate("MainWindow", "\n"
"외+기"))
        item = self.tableWidget_4.horizontalHeaderItem(118)
        item.setText(_translate("MainWindow", "\n"
"금융투자"))
        item = self.tableWidget_4.horizontalHeaderItem(119)
        item.setText(_translate("MainWindow", "\n"
"보험"))
        item = self.tableWidget_4.horizontalHeaderItem(120)
        item.setText(_translate("MainWindow", "\n"
"투신"))
        item = self.tableWidget_4.horizontalHeaderItem(121)
        item.setText(_translate("MainWindow", "\n"
"기타금융"))
        item = self.tableWidget_4.horizontalHeaderItem(122)
        item.setText(_translate("MainWindow", "\n"
"은행"))
        item = self.tableWidget_4.horizontalHeaderItem(123)
        item.setText(_translate("MainWindow", "\n"
"연기금"))
        item = self.tableWidget_4.horizontalHeaderItem(124)
        item.setText(_translate("MainWindow", "\n"
"사모펀드"))
        item = self.tableWidget_4.horizontalHeaderItem(125)
        item.setText(_translate("MainWindow", "\n"
"국가"))
        item = self.tableWidget_4.horizontalHeaderItem(126)
        item.setText(_translate("MainWindow", "\n"
"기타법인"))
        item = self.tableWidget_4.horizontalHeaderItem(127)
        item.setText(_translate("MainWindow", "\n"
"내외국인"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "매집량 추세"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "일자"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "주가"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "개인"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "외+기관"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "세력"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "기관"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "세력분산"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "금융투자"))
        item = self.tableWidget_5.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "보험"))
        item = self.tableWidget_5.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "투신"))
        item = self.tableWidget_5.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "기타금융"))
        item = self.tableWidget_5.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "은행"))
        item = self.tableWidget_5.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "연기금"))
        item = self.tableWidget_5.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "사모펀드"))
        item = self.tableWidget_5.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "국가"))
        item = self.tableWidget_5.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "내외국인"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "매집량 분포"))

from matplotlibWidgetFile import matplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

