print("module_1 script is running.....")
print(dir())
# print("__builtins__ : ",__builtins__)
# print("__cached__ : ",__cached__)
# print("__doc__ : ",__doc__)
# print("__file__ : ",__file__)
# print("__loader__ : ",__loader__)
# print("__name__ : ",__name__)
# print("__package__ : ",__package__)
# print("__spec__ : ",__spec__)
print("module_1 script is runned.")
print("")